최근 검색어 cell 별 삭제 구현
Korea-Certified-Store/iOS pull request #229
Opened 2024-02-12 20:35 UTC by k2645

## ⭐️ Issue Number

- #228 

## 🚩 Summary

- 최근 검색어 cell의 삭제 기능 구현

![Simulator Screen Recording - iPhone 15 - 2024-02-13 at 05 10 03](https://github.com/Korea-Certified-Store/iOS/assets/62226667/ef8c7b76-93bd-4c8b-8412-de0ad4e41844)

## 🛠️ Technical Concerns

### 특정 Button Tap 이벤트 생성

최근 검색어 삭제를 구현하기 위해서는 cell별로 다른 button tap 이벤트가 필요했다.
`Reactive where Base:`를 사용하면 특정 class 내부의 스트림을 class 외부에서 구독할 수 있다.
다음과 같이 코드를 작성하여 `RecentHistoryTableViewCell` 내부에 있는 `removeKeywordButton.rx.tap`에 의해 발생한 스트림을 구독할 수 있도록 해주었다.

```swift
extension Reactive where Base: RecentHistoryTableViewCell {
    var removeKeywordButtonTapped: ControlEvent<Void> { base.removeKeywordButton.rx.tap }
}
```

그리고 위 스트림을 클래스 밖에서 구독할 땐 다음과 같이 해주었다.

```swift
cell.rx.removeKeywordButtonTapped
    .bind { [weak self] in
        self?.viewModel.action(input: .deleteSearchHistory(index: indexPath.row))
    }
```

### Cell Dispose

cell button을 구독하면 dispose하는 작업도 필요했다. 
cell 내부에 있는 버튼에 대한 구독은 `SearchViewController`에서 해주지만 스트림이 발생한 곳은 cell 내부이기 때문에 dispose는 cell 내부에 존재하는 `disposeBag`을 사용하여 dispose해주어야했다.

```swift
cell.rx.removeKeywordButtonTapped
    .bind { [weak self] in
        ...
    }
    .disposed(by: cell.disposedBag)
```

### applySnapshotUsingReloadData

현재 UserDefaults를 삭제하는 로직은 indexPath 값을 통해 배열의 위치를 찾아들어가 삭제하는 방식을 채택하고있다.
보통은 dataSource를 update해줄때 `apply`를 사용하는데, `apply`를 통해 DataSource를 바꿔주면 cell의 indexPath값은 변하지 않는 이슈가 발생하였다. 이렇게 되면 제대로된 UserDefaults 배열의 위치로 찾아들어가지 못하게된다.
따라서 `applySnapshotUsingReloadData`를 사용하여 dataSource가 바뀌는 즉시 indexPath 또한 업데이트 해주는 방식으로 코드를 진행하였다.

2024-02-12 20:40 UTC, SungMinCho-Kor requested changes
고생하셨습니다!

2024-02-12 20:40 UTC, SungMinCho-Kor commented on KCS/KCS/Presentation/Search/View/RecentHistoryTableViewCell.swift
> +    }
disposeBag을 초기화하는 이유가 궁금합니다.

2024-02-12 20:40 UTC, SungMinCho-Kor commented on KCS/KCS/Presentation/Search/View/RecentHistoryTableViewCell.swift
> +    let removeKeywordButton = UIButton()
private을 제거하면 객체지향 프로그래밍의 캡슐화가 약화될 것 같습니다.
private을 추가하고 setUIContents에 매개변수를 추가하여 주입하는 방식으로 해결할 수 있지 않을까요?

2024-02-13 10:35 UTC, k2645 commented on KCS/KCS/Presentation/Search/View/RecentHistoryTableViewCell.swift
> +    }
Cell 내부에서 스트림이 발생하고, 이 스트림을 외부에서 구독하여 사용하게 되는데 이 경우 prepareForReuse() 에서 명시적 구독 해제를 해주지 않으면 재활용하게되는 다른 셀에서 재활용된 구독을 하기 때문에 원하지 않는 엉뚱한 값을 받게 될 수 있기 때문에 초기화를 해주었습니다.

2024-02-13 11:00 UTC, k2645 commented on KCS/KCS/Presentation/Search/View/RecentHistoryTableViewCell.swift
> +    let removeKeywordButton = UIButton()
넵! 밖에서 의존성을 주입시키는 방식으로 수정하였습니다!

2024-02-13 13:28 UTC, SungMinCho-Kor approved these changes
고생하셨습니다.
추후에 Reload 하는 부분을 리팩토링하면 좋을 것 같아요.

2024-02-13 13:28 UTC, merged