NewStoreRequestViewModelImpl 테스트
Korea-Certified-Store/iOS pull request #388
Opened 2024-03-05 16:06 UTC by k2645

## ⭐️ Issue Number

- #387 

## 🚩 Summary

- NewStoreRequestViewModelImpl 테스트 코드를 작성한다.

![image](https://github.com/Korea-Certified-Store/iOS/assets/62226667/e7875650-2dbd-4990-93f4-ca8dc9305a00)

## 🛠️ Technical Concerns

### RxTest

이 전의 테스트들과는 다르게 ViewModel을 테스트 하기 위해서는 input값을 주고 그에 대한 결과값을 방출하기 전에 Output 옵저버들을 구독해야 했다.
이를 위해서 TestScheduler를 생성하고 테스트 하려는 Output의 값을 미리 subscribe를 해준 뒤 테스트를 진행하였다.
```swift
  private var scheduler: TestScheduler!
  
  override func setUp() {
      scheduler = TestScheduler(initialClock: 0)
      disposeBag = DisposeBag()
  }
  
  func test_제목_칸이_빈칸인_채로_수정을_마친_경우() {
      // Given
      let observer = scheduler.createObserver(Void.self)
      newStoreRequestViewModel.titleWarningOutput
          .subscribe(observer)
          .disposed(by: disposeBag)
      
      // When
      newStoreRequestViewModel.action(input: .endEdit(text: constant.emptyTestText, inputCase: .title))
      
      // Then
      XCTAssertNotNil(observer.events.first)
  }
```

## 🙂 To Reviwer

- 문법으로 인해 들어간 Switch문의 Default 때문에 Coverage 100%가 나오지 않았습니다.. Default로 가게되면 break로 아무런 일이 일어나지 않아 따로 테스트를 진행하지 않았습니다. 감안하고 봐주시면 감사하겠습니다!

2024-03-05 16:28 UTC, SungMinCho-Kor requested changes
고생하셨습니다!

2024-03-05 16:28 UTC, SungMinCho-Kor commented on KCS/KCSUnitTest/TestDouble/UseCase/StubFailurePostNewStoreUseCase.swift
> +    var repository: PostNewStoreRepository
let으로 선언하는 것이 좋을 것 같아요~
아래도 마찬가지 입니다!

2024-03-05 16:28 UTC, SungMinCho-Kor commented on KCS/KCSUnitTest/TestDouble/UseCase/StubSuccessPostNewStoreUseCase.swift
> +    var repository: PostNewStoreRepository
여기두요~

2024-03-05 16:28 UTC, SungMinCho-Kor commented on KCS/KCSUnitTest/TestDouble/UseCase/StubSuccessPostNewStoreUseCase.swift
> +        }
굳이 이렇게 만들지 않고 .just(())로 해도 될 것 같아요!

2024-03-05 16:28 UTC, SungMinCho-Kor commented on KCS/KCSUnitTest/ViewModelTest/NewStoreRequestViewModelImplTests.swift
> +        }
True가 아닌 경우에 자동적으로 Fail이 됩니다. if let을 사용하지 않아도 될 것 같아요!

2024-03-05 17:03 UTC, k2645 commented on KCS/KCSUnitTest/ViewModelTest/NewStoreRequestViewModelImplTests.swift
> +        }
위 경우 if let구문이 옵셔널 추출용으로 사용된 케이스이기 때문에 nil일 경우 fail이 뜨게 하기 위해서 else처리를 해주었습니다!

2024-03-06 13:15 UTC, SungMinCho-Kor approved these changes
👍

2024-03-06 13:37 UTC, merged