StoreUpdateRequestViewModelImpl 테스트
Korea-Certified-Store/iOS pull request #389
Opened 2024-03-05 16:23 UTC by SungMinCho-Kor

## ⭐️ Issue Number

- #375

## 🚩 Summary

- 잘못된 함수 이름 변경 (Fetch -> Set)
- init과 ViewDidLoad 싱크 문제 해결 (네비게이션바가 없어지는 현상 제거)
- 완료 버튼 활성화 조건 수정
- StoreUpdateRequestViewModelImpl 테스트

## 🛠️ Technical Concerns

### init과 ViewDidLoad

init에서 UI와 관련된 코드를 작성하는 순간 ViewDidLoad가 호출되는 것을 이제서야 알게 됐다.
UI와 관련된 코드는 ViewDidLoad로 옮기고 기본적인 설정만 init에서 해줘야 한다.

2024-03-05 16:44 UTC, k2645 requested changes
전반적으로 XCTAssertTrue/False 대신 XCTAssertEqual을 사용하셨는데 전자의 코드를 사용하는 것이 더 좋을 것 같다는 생각이 듭니다!
잘못 구현된 부분도 고쳐주시느라 정말 수고하셨습니다!

2024-03-05 16:44 UTC, k2645 commented on KCS/KCS.xcodeproj/project.pbxproj
>  		592D0E152B94324E003E90F9 /* SpySpyDeleteRecentSearchHistoryRepository.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = SpySpyDeleteRecentSearchHistoryRepository.swif
파일명 잘못된 부분 고쳐주시면 좋을 것 같습니다.

2024-03-05 16:44 UTC, k2645 commented on KCS/KCSUnitTest/TestDouble/UseCase/StubFetchStoreIDUseCase.swift
> +}
Success와 Failure의 경우는 다른 파일들과 마찬가지로 통일성 있게 파일을 따로 나눠주시면 좋을 것 같습니다!
아래 StubStoreUpdateRequestUseCase도 마찬가지입니다.

2024-03-05 16:44 UTC, k2645 commented on KCS/KCSUnitTest/ViewModelTest/StoreUpdateRequestViewModelImplTests.swift
> +    private var spySetStoreIDUseCase: SpySetStoreIDUseCase!
모든 UseCase들을 선언부에 선언해둘 필요는 없을 것 같습니다. 해당 UseCase가 필요한 test 함수 내부에서 생성하여 사용하면 되지 않을까요?

2024-03-05 16:44 UTC, k2645 commented on KCS/KCSUnitTest/ViewModelTest/StoreUpdateRequestViewModelImplTests.swift
> +        XCTAssertEqual(completeButtonIsEnabledObserver.events.first?.value.element, false)
이 경우에 XCTAssertFalse가 있는데 XCTAssertEqual을 사용하신 이유가 궁금합니다.

2024-03-05 17:00 UTC, SungMinCho-Kor commented on KCS/KCSUnitTest/ViewModelTest/StoreUpdateRequestViewModelImplTests.swift
> +    private var spySetStoreIDUseCase: SpySetStoreIDUseCase!
코드에서 중복적으로 사용되는 곳이 많아서 선언해두고 사용했습니다.

2024-03-05 17:01 UTC, SungMinCho-Kor commented on KCS/KCSUnitTest/ViewModelTest/StoreUpdateRequestViewModelImplTests.swift
> +        XCTAssertEqual(completeButtonIsEnabledObserver.events.first?.value.element, false)
XCTAssertFalse는 옵셔널을 검사할 수 없습니다.
if let 혹은 guard let으로 옵셔널을 검사한 후 XCTAssertFalse를 사용하는 것은 검사를 중복하여 진행하는 것과 같다고 판단하여 한 번에 처리할 수 있는 XCTAssertEqual을 사용했습니다.

2024-03-06 13:11 UTC, k2645 approved these changes
👍

2024-03-06 13:14 UTC, merged